name: saraneladmin
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.1
  cloud_firestore: ^4.9.1
  firebase_storage: ^11.2.6
  firebase_auth: ^4.9.0
  google_nav_bar: ^5.0.6
  equatable: ^2.0.5
  cached_network_image: ^3.2.3
  google_fonts: ^5.1.0
  url_launcher: ^6.1.12
  shared_preferences: ^2.2.0
  image_picker: ^1.0.2
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  universal_html: ^2.2.4
  data_table_2: ^2.5.8
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png


  